# 构建阶段
FROM golang:1.20 AS builder  # 升级Go版本 [[6]]
ENV GOPROXY=https://goproxy.cn,direct  # 设置代理 [[8]]
WORKDIR /go/src/ehang.io/nps

# 分阶段下载依赖 [[9]]
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-w -s -extldflags -static" -o nps ./cmd/nps/nps.go

# 最终镜像
FROM scratch
COPY --from=builder /go/src/ehang.io/nps/nps /
COPY --from=builder /go/src/ehang.io/nps/web /web
VOLUME /conf
CMD ["/nps"]
